"""Add parent_id to skill_categories

Revision ID: c9c46401e330
Revises: f5924e7901b8
Create Date: 2026-07-25 10:50:43.027213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9c46401e330'
down_revision: Union[str, None] = 'f5924e7901b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skill_categories', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'skill_categories', 'skill_categories', ['parent_id'], ['id'], ondelete='CASCADE')
    op.alter_column('skills', 'skill_category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('skills', 'skill_category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'skill_categories', type_='foreignkey')
    op.drop_column('skill_categories', 'parent_id')
    # ### end Alembic commands ###
