"""Add skill categories and skills

Revision ID: f5924e7901b8
Revises: 74192b125dc3
Create Date: 2026-07-25 10:30:57.402730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5924e7901b8'
down_revision: Union[str, None] = '74192b125dc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skill_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_skill_categories_id'), 'skill_categories', ['id'], unique=False)
    op.add_column('skills', sa.Column('skill_category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'skills', 'skill_categories', ['skill_category_id'], ['id'], ondelete='CASCADE')
    op.drop_column('skills', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skills', sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'skills', type_='foreignkey')
    op.drop_column('skills', 'skill_category_id')
    op.drop_index(op.f('ix_skill_categories_id'), table_name='skill_categories')
    op.drop_table('skill_categories')
    # ### end Alembic commands ###
